/* Espace membre — responsive, server-aware, GitHub fallback. */
(function () {
  'use strict';
  var PURCHASES_KEY='sophia_demo_purchases', SAVED_KEY='sophia_demo_saved_articles';
  var gate=document.querySelector('[data-member-gate]'), app=document.querySelector('[data-member-app]');
  if(!gate||!app) return;
  function readSession(){ try { var s=JSON.parse(localStorage.getItem('sophia_demo_session')||'null'); return s&&s.demo===true&&s.email?s:null; } catch(e){return null;} }
  var session=readSession(); if(!session) return;
  gate.hidden=true; app.hidden=false;
  var state={ purchases:[], saved:[] };
  function loadLocal(){
    try{state.purchases=JSON.parse(localStorage.getItem(PURCHASES_KEY)||'[]');}catch(e){state.purchases=[];}
    try{state.saved=JSON.parse(localStorage.getItem(SAVED_KEY)||'[]');}catch(e){state.saved=[];}
  }
  function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function emptyPanel(title,text){return '<div class="member-card"><div class="member-card-head"><h2>'+esc(title)+'</h2></div><div class="empty-state"><p class="empty-state-mark" aria-hidden="true">✦</p><h3 class="empty-state-title">'+esc(text)+'</h3><p>Les contenus apparaîtront ici au fil de vos lectures et inscriptions.</p></div></div>';}
  function money(v){return esc(v||'CHF 0.00');}
  function saveLocal(){localStorage.setItem(PURCHASES_KEY,JSON.stringify(state.purchases));localStorage.setItem(SAVED_KEY,JSON.stringify(state.saved));}
  var panels={
    profil:function(){return '<div class="member-card"><div class="member-card-head"><div><h2>Profil</h2><p class="member-card-muted">Votre espace personnel et vos accès.</p></div><span class="badge badge-neutral">'+esc(session.role==='owner'?'Propriétaire':'Membre')+'</span></div><div class="stat-row"><div class="stat-box"><p class="num">'+state.purchases.length+'</p><p class="lbl">Contenus débloqués</p></div><div class="stat-box"><p class="num">'+state.saved.length+'</p><p class="lbl">Articles enregistrés</p></div></div><div class="table-wrap"><table class="data"><tbody><tr>'+cell('Nom',esc(session.name))+'</tr><tr>'+cell('E-mail','<code>'+esc(session.email)+'</code>')+'</tr><tr>'+cell('Session','Démonstration — authentification via le serveur lorsque disponible.')+'</tr></tbody></table></div></div>';},
    achats:function(){if(!state.purchases.length)return emptyPanel('Contenus achetés','Aucun contenu débloqué pour le moment');return '<div class="member-card"><div class="member-card-head"><div><h2>Contenus achetés</h2><p class="member-card-muted">Vos accès numériques.</p></div></div><div class="table-wrap"><table class="data"><thead><tr><th>Contenu</th><th>Type</th><th>Montant</th><th>Accès</th></tr></thead><tbody>'+state.purchases.map(function(x){return '<tr>'+cell('Contenu',esc(x.title))+cell('Type',esc(x.kind))+cell('Montant',money(x.price))+cell('Accès','<a class="link-more" href="'+esc(x.url)+'">Ouvrir →</a>')+'</tr>';}).join('')+'</tbody></table></div></div>';},
    enregistres:function(){if(!state.saved.length)return emptyPanel('Articles enregistrés','Aucun article enregistré pour le moment');return '<div class="member-card"><div class="member-card-head"><div><h2>Articles enregistrés</h2><p class="member-card-muted">Vos lectures mises de côté.</p></div></div><div class="table-wrap"><table class="data"><thead><tr><th>Article</th><th>Catégorie</th><th>Action</th></tr></thead><tbody>'+state.saved.map(function(x){return '<tr>'+cell('Article',esc(x.title))+cell('Catégorie',esc(x.category||'Article'))+cell('Action','<a class="link-more" href="'+esc(x.url)+'">Lire →</a>')+'</tr>';}).join('')+'</tbody></table></div></div>';},
    cours:function(){var p=state.purchases.filter(function(x){return String(x.kind).toLowerCase().indexOf('cours')!==-1;});if(!p.length)return emptyPanel('Mes cours','Aucune inscription pour le moment');return '<div class="member-card"><div class="member-card-head"><div><h2>Mes cours</h2><p class="member-card-muted">Vos inscriptions et accès.</p></div></div><div class="table-wrap"><table class="data"><thead><tr><th>Cours</th><th>Montant</th><th>Accès</th></tr></thead><tbody>'+p.map(function(x){return '<tr>'+cell('Cours',esc(x.title))+cell('Montant',money(x.price))+cell('Accès','<a class="link-more" href="'+esc(x.url)+'">Ouvrir →</a>')+'</tr>';}).join('')+'</tbody></table></div></div>';},
    commandes:function(){if(!state.purchases.length)return emptyPanel('Commandes','Aucune commande pour le moment');return '<div class="member-card"><div class="member-card-head"><div><h2>Commandes</h2><p class="member-card-muted">Historique des achats simulés.</p></div></div><div class="table-wrap"><table class="data"><thead><tr><th>Référence</th><th>Contenu</th><th>Montant</th><th>Statut</th></tr></thead><tbody>'+state.purchases.map(function(x){return '<tr>'+cell('Référence','<code>'+esc(x.ref)+'</code>')+cell('Contenu',esc(x.title))+cell('Montant',money(x.price))+cell('Statut','<span class="badge badge-pub">Payée (simulation)</span>')+'</tr>';}).join('')+'</tbody></table></div><p class="demo-note">◈ Aucune transaction réelle n’a été effectuée.</p></div>';},
    reglages:function(){return '<div class="member-card"><div class="member-card-head"><div><h2>Réglages</h2><p class="member-card-muted">Personnalisez les informations affichées.</p></div></div><form data-member-settings novalidate><div class="form-grid"><div class="field"><label for="ms-name">Nom affiché</label><input id="ms-name" value="'+esc(session.name)+'"></div><button class="btn btn-primary" type="submit">Enregistrer (démo)</button><p class="form-status" data-form-status role="status" aria-live="polite"></p></div></form><hr class="member-divider"><h3 class="member-subheading">Données locales</h3><p class="member-card-muted">Effacement local uniquement si le site est utilisé via GitHub Pages.</p><button class="btn btn-outline btn-small" type="button" data-member-reset>Effacer mes données de démonstration</button></div>';}
  };
  function cell(label,html){return '<th scope="row">'+esc(label)+'</th><td data-label="'+esc(label)+'">'+html+'</td>';}
  var panel=document.querySelector('[data-member-panel]'), nav=document.querySelector('[data-member-nav]');
  function wire(){
    var settings=panel.querySelector('[data-member-settings]');
    if(settings) settings.addEventListener('submit',async function(e){e.preventDefault();var value=settings.querySelector('#ms-name').value.trim()||session.name;session.name=value;localStorage.setItem('sophia_demo_session',JSON.stringify(session));var st=settings.querySelector('[data-form-status]');st.textContent='Nom enregistré.';st.classList.add('ok');try{if(window.SophiaAPI)await window.SophiaAPI.put('/api/member/profile',{name:value});}catch(err){} });
    var reset=panel.querySelector('[data-member-reset]');
    if(reset) reset.addEventListener('click',async function(){try{if(window.SophiaAPI)await window.SophiaAPI.post('/api/auth/reset-demo');}catch(e){} ['sophia_demo_session','sophia_demo_purchases','sophia_demo_saved_articles','sophia_demo_newsletter','sophia_demo_proposals'].forEach(function(k){localStorage.removeItem(k);});location.href='../connexion/';});
  }
  function show(tab){tab=panels[tab]?tab:'profil';panel.innerHTML=panels[tab]();nav.querySelectorAll('a[data-tab]').forEach(function(a){a.setAttribute('aria-current',String(a.getAttribute('data-tab')===tab));});wire();}
  nav.addEventListener('click',function(e){var a=e.target.closest('a');if(!a)return;if(a.hasAttribute('data-logout')){e.preventDefault();(async function(){try{if(window.SophiaAPI)await window.SophiaAPI.post('/api/auth/logout');}catch(err){}if(window.AuthSession)window.AuthSession.clear();else localStorage.removeItem('sophia_demo_session');location.href='../connexion/';})();return;}var tab=a.getAttribute('data-tab');if(tab){e.preventDefault();history.replaceState(null,'','#'+tab);show(tab);}});
  loadLocal();
  // Prefer server state when available — local data stays as a graceful offline fallback.
  if(window.SophiaAPI){window.SophiaAPI.get('/api/member/summary').then(function(data){if(data&&data.session){session=data.session;localStorage.setItem('sophia_demo_session',JSON.stringify(session));}if(data&&Array.isArray(data.purchases))state.purchases=data.purchases;if(data&&Array.isArray(data.saved))state.saved=data.saved;show((location.hash||'#profil').slice(1));}).catch(function(){show((location.hash||'#profil').slice(1));});}else{show((location.hash||'#profil').slice(1));}
  window.addEventListener('hashchange',function(){show((location.hash||'#profil').slice(1));});
})();
