import http from 'node:http';
import path from 'node:path';
import fs from 'node:fs/promises';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { Pool } from 'pg';
import { articles } from '../src/data/demo/articles.js';
import { courses } from '../src/data/demo/content.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SITE_ROOT = path.join(ROOT, 'docs');
const PORT = Number(process.env.PORT || 10000);
const SESSION_TTL_DAYS = 14;
const DEMO_MODE = String(process.env.DEMO_MODE || 'true').toLowerCase() !== 'false';
const SESSION_SECRET = process.env.SESSION_SECRET || 'change-me-for-production';

let pool = process.env.DATABASE_URL ? new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false }, max: 5 }) : null;
const memory = { users: new Map(), sessions: new Map(), purchases: [], saved: [], newsletter: new Set(), proposals: [], contacts: [], adminState: { deleted: {}, status: {} }, settings: {} };

function hashPassword(password, salt = crypto.randomBytes(16).toString('hex')) {
  const hash = crypto.scryptSync(password, salt, 64).toString('hex');
  return `${salt}:${hash}`;
}
function verifyPassword(password, encoded) {
  try { const [salt, hash] = String(encoded).split(':'); const actual = crypto.scryptSync(password, salt, 64).toString('hex'); return crypto.timingSafeEqual(Buffer.from(actual,'hex'), Buffer.from(hash,'hex')); } catch { return false; }
}
function sha(value) { return crypto.createHash('sha256').update(value).digest('hex'); }
function token() { return crypto.randomBytes(32).toString('base64url'); }
function cookieToken(req) { const m=(req.headers.cookie||'').match(/(?:^|;)\s*sophia_session=([^;]+)/); return m?decodeURIComponent(m[1]):null; }
function setCookie(res, value, maxAge) { const secure = (process.env.COOKIE_SECURE === 'true' || process.env.NODE_ENV === 'production' || process.env.RENDER === 'true') ? '; Secure' : ''; res.setHeader('Set-Cookie', `sophia_session=${encodeURIComponent(value)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}${secure}`); }
function clearCookie(res) { setCookie(res, '', 0); }
function json(res,status,data,extra={}) { res.writeHead(status,{ 'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...extra });res.end(JSON.stringify(data)); }
function htmlHeaders(res, contentType='text/html; charset=utf-8') { res.setHeader('Content-Type',contentType);res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()'); }
function sameOrigin(req) { if(!['POST','PUT','PATCH','DELETE'].includes(req.method))return true;const origin=req.headers.origin;if(!origin)return true;try{return new URL(origin).host===req.headers.host;}catch{return false;} }
async function body(req){let raw='';for await(const c of req)raw+=c;if(!raw)return {};try{return JSON.parse(raw);}catch{return {};}}
async function query(text,values=[]){if(!pool)throw new Error('database-unavailable');const client=await pool.connect();try{return await client.query(text,values);}finally{client.release();}}
async function initDb(){if(!pool)return;await query(`CREATE TABLE IF NOT EXISTS users (id BIGSERIAL PRIMARY KEY,email TEXT NOT NULL UNIQUE,name TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'member',password_hash TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires_at TIMESTAMPTZ NOT NULL);CREATE TABLE IF NOT EXISTS purchases (id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,ref TEXT NOT NULL UNIQUE,slug TEXT NOT NULL,kind TEXT NOT NULL,title TEXT NOT NULL,price_cents INTEGER NOT NULL,url TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user_id,slug));CREATE TABLE IF NOT EXISTS saved_articles (user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,slug TEXT NOT NULL,title TEXT NOT NULL,category TEXT NOT NULL,url TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(user_id,slug));CREATE TABLE IF NOT EXISTS newsletter_subscribers (email TEXT PRIMARY KEY,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS contact_messages (id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL,subject TEXT NOT NULL,message TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS proposals (id BIGSERIAL PRIMARY KEY,ref TEXT NOT NULL UNIQUE,appel TEXT NOT NULL,name TEXT NOT NULL,email TEXT NOT NULL,title TEXT NOT NULL,summary TEXT NOT NULL,message TEXT NOT NULL,file_name TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'En attente',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS admin_state (key TEXT PRIMARY KEY,value JSONB NOT NULL);CREATE TABLE IF NOT EXISTS site_settings (key TEXT PRIMARY KEY,value TEXT NOT NULL);`);
  for(const d of [['demo-owner@example.test','Propriétaire (démo)','owner'],['demo-member@example.test','Membre (démo)','member']]){const found=await query('SELECT id FROM users WHERE lower(email)=lower($1) LIMIT 1',[d[0]]);if(!found.rowCount)await query('INSERT INTO users(email,name,role,password_hash) VALUES($1,$2,$3,$4)',[d[0],d[1],d[2],hashPassword('DemoOnly-2026!')]);}
  const member=await query('SELECT id FROM users WHERE lower(email)=lower($1) LIMIT 1',['demo-member@example.test']);if(member.rowCount){await query('INSERT INTO saved_articles(user_id,slug,title,category,url) VALUES($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING',[member.rows[0].id,'lire-a-l-ere-des-ecrans','Lire à l’ère des écrans','Essai','../articles/lire-a-l-ere-des-ecrans/']);await query('INSERT INTO saved_articles(user_id,slug,title,category,url) VALUES($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING',[member.rows[0].id,'la-bibliotheque-comme-paysage','La bibliothèque comme paysage','Chronique','../articles/la-bibliotheque-comme-paysage/']);}
}
async function userFromSession(req){const raw=cookieToken(req);if(!raw)return null;const h=sha(raw);if(pool){const r=await query('SELECT u.id,u.email,u.name,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>NOW()', [h]);return r.rows[0]||null;}const s=memory.sessions.get(h);if(!s||s.expiresAt<Date.now())return null;return memory.users.get(s.userId)||Array.from(memory.users.values()).find(u=>u.id===s.userId)||null;}
async function makeSession(res,user){const raw=token(), h=sha(raw), expiry=new Date(Date.now()+SESSION_TTL_DAYS*86400000);if(pool)await query('INSERT INTO sessions(token_hash,user_id,expires_at) VALUES($1,$2,$3)',[h,user.id,expiry]);else memory.sessions.set(h,{userId:user.id,expiresAt:expiry.getTime()});setCookie(res,raw,SESSION_TTL_DAYS*86400);return {demo:true,email:user.email,name:user.name,role:user.role,since:new Date().toISOString()};}
async function createUser({email,name,password,role='member'}){const clean=email.trim().toLowerCase();if(pool){const existing=await query('SELECT id FROM users WHERE lower(email)=lower($1)',[clean]);if(existing.rowCount)throw new Error('Cette adresse e-mail est déjà utilisée.');const r=await query('INSERT INTO users(email,name,role,password_hash) VALUES($1,$2,$3,$4) RETURNING id,email,name,role',[clean,name,role,hashPassword(password)]);return r.rows[0];}if(memory.users.has(clean))throw new Error('Cette adresse e-mail est déjà utilisée.');const u={id:crypto.randomUUID(),email:clean,name,role};u.passwordHash=hashPassword(password);memory.users.set(clean,u);return u;}
async function loginUser(email,password){const clean=email.trim().toLowerCase();if(pool){const r=await query('SELECT id,email,name,role,password_hash FROM users WHERE lower(email)=lower($1) LIMIT 1',[clean]);const u=r.rows[0];if(!u||!verifyPassword(password,u.password_hash))throw new Error('Identifiants incorrects.');return u;}let u=memory.users.get(clean);if(!u&&DEMO_MODE){const demo={ 'demo-owner@example.test':['Propriétaire (démo)','owner'], 'demo-member@example.test':['Membre (démo)','member'] }[clean];if(demo)u=memory.users.get(clean)||await createUser({email:clean,name:demo[0],password:'DemoOnly-2026!',role:demo[1]});}if(!u||!verifyPassword(password,u.passwordHash))throw new Error('Identifiants incorrects.');return u;}
function publicSession(u){return u?{demo:true,email:u.email,name:u.name,role:u.role,since:new Date().toISOString()}:null;}
function findItem(slug,kind){const list=kind==='cours'?courses.filter(x=>x.slug===slug):articles.filter(x=>x.slug===slug&&x.premium);return list[0]||null;}
function adminStateBase(){return JSON.parse(JSON.stringify(memory.adminState));}
async function getAdminState(){if(!pool)return adminStateBase();const r=await query("SELECT value FROM admin_state WHERE key='state'");return r.rowCount?r.rows[0].value:adminStateBase();}
async function updateAdminState({collection,key,action,value}){const st=await getAdminState();st.deleted=st.deleted||{};st.status=st.status||{};if(action==='delete'){st.deleted[collection]=st.deleted[collection]||[];if(!st.deleted[collection].includes(key))st.deleted[collection].push(key);}else if(action==='status'){st.status[collection]=st.status[collection]||{};st.status[collection][key]=value;}if(pool)await query("INSERT INTO admin_state(key,value) VALUES('state',$1) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value",[st]);else memory.adminState=st;return st;}

async function api(req,res,url){
  if(!sameOrigin(req))return json(res,403,{message:'Requête refusée.'});
  const p=url.pathname;
  if(p==='/api/health')return json(res,200,{ok:true,database:!!pool,mode:pool?'neon':'memory'});
  if(p==='/api/auth/me'&&req.method==='GET'){return json(res,200,{session:publicSession(await userFromSession(req))});}
  if(p==='/api/auth/login'&&req.method==='POST'){const b=await body(req);if(!b.email||!b.password)return json(res,400,{message:'E-mail et mot de passe requis.'});try{const u=await loginUser(b.email,b.password);return json(res,200,{session:await makeSession(res,u)});}catch(e){return json(res,401,{message:e.message});}}
  if(p==='/api/auth/register'&&req.method==='POST'){const b=await body(req);if(!b.email||!b.password||!b.name)return json(res,400,{message:'Nom, e-mail et mot de passe requis.'});try{const u=await createUser({email:b.email,name:b.name,password:b.password});return json(res,201,{session:await makeSession(res,u)});}catch(e){return json(res,409,{message:e.message});}}
  if(p==='/api/auth/logout'&&req.method==='POST'){const raw=cookieToken(req);if(raw&&pool)await query('DELETE FROM sessions WHERE token_hash=$1',[sha(raw)]);if(raw&&!pool)memory.sessions.delete(sha(raw));clearCookie(res);return json(res,200,{ok:true});}
  const user=await userFromSession(req);
  if(p==='/api/auth/reset-demo'&&req.method==='POST'){if(user){const raw=cookieToken(req);if(raw&&pool)await query('DELETE FROM sessions WHERE token_hash=$1',[sha(raw)]);if(raw&&!pool)memory.sessions.delete(sha(raw));}clearCookie(res);return json(res,200,{ok:true});}
  if(p==='/api/member/summary'&&req.method==='GET'){if(!user)return json(res,401,{message:'Connexion requise.'});if(pool){const [pr,sv]=await Promise.all([query('SELECT ref,slug,kind,title,\'CHF \'||to_char(price_cents/100.0,\'FM999990.00\') price,url,created_at date FROM purchases WHERE user_id=$1 ORDER BY created_at DESC',[user.id]),query('SELECT slug,title,category,url FROM saved_articles WHERE user_id=$1 ORDER BY created_at DESC',[user.id])]);return json(res,200,{session:publicSession(user),purchases:pr.rows,saved:sv.rows});}return json(res,200,{session:publicSession(user),purchases:memory.purchases.filter(x=>x.userId===user.id),saved:memory.saved.filter(x=>x.userId===user.id)});}
  if(p==='/api/member/profile'&&req.method==='PUT'){if(!user)return json(res,401,{message:'Connexion requise.'});const b=await body(req);if(!b.name)return json(res,400,{message:'Nom requis.'});if(pool)await query('UPDATE users SET name=$1 WHERE id=$2',[b.name,user.id]);else{user.name=b.name;}return json(res,200,{ok:true});}
  if(p==='/api/member/saved'&&req.method==='POST'){if(!user)return json(res,401,{message:'Connexion requise.'});const b=await body(req);if(!b.slug||!b.title)return json(res,400,{message:'Article invalide.'});if(pool){await query('INSERT INTO saved_articles(user_id,slug,title,category,url) VALUES($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING',[user.id,b.slug,b.title,b.category||'Article',b.url||`../articles/${b.slug}/`]);}else{if(!memory.saved.some(x=>x.userId===user.id&&x.slug===b.slug))memory.saved.push({userId:user.id,slug:b.slug,title:b.title,category:b.category||'Article',url:b.url||`../articles/${b.slug}/`});}return json(res,201,{ok:true});}
  if(p==='/api/checkout'&&req.method==='POST'){if(!user)return json(res,401,{message:'Connexion requise.'});const b=await body(req),item=findItem(b.slug,b.kind);if(!item)return json(res,400,{message:'Contenu introuvable.'});const ref='CMD-2026-'+String(Math.floor(1000+Math.random()*9000)),urlPath=b.kind==='cours'?`../cours/${item.slug}/`:`../articles/${item.slug}/`;if(pool){try{await query('INSERT INTO purchases(user_id,ref,slug,kind,title,price_cents,url) VALUES($1,$2,$3,$4,$5,$6,$7)',[user.id,ref,item.slug,b.kind==='cours'?'Cours':'Article premium',item.title,Math.round(Number(item.price)*100),urlPath]);}catch(e){if(e.code==='23505')return json(res,409,{message:'Vous possédez déjà cet élément.'});throw e;}}else{if(memory.purchases.some(x=>x.userId===user.id&&x.slug===item.slug))return json(res,409,{message:'Vous possédez déjà cet élément.'});memory.purchases.push({userId:user.id,ref,slug:item.slug,kind:b.kind==='cours'?'Cours':'Article premium',title:item.title,price:`CHF ${Number(item.price).toFixed(2)}`,url:urlPath,date:new Date().toISOString()});}return json(res,201,{ok:true,ref});}
  if(p==='/api/newsletter'&&req.method==='POST'){const b=await body(req),email=String(b.email||'').trim().toLowerCase();if(!email)return json(res,400,{message:'E-mail requis.'});if(pool){const r=await query('INSERT INTO newsletter_subscribers(email) VALUES($1) ON CONFLICT DO NOTHING RETURNING email',[email]);return json(res,200,{ok:true,alreadySubscribed:!r.rowCount});}const already=memory.newsletter.has(email);memory.newsletter.add(email);return json(res,200,{ok:true,alreadySubscribed:already});}
  if(p==='/api/contact'&&req.method==='POST'){const b=await body(req);if(!b.name||!b.email||!b.subject||!b.message)return json(res,400,{message:'Champs requis manquants.'});if(pool)await query('INSERT INTO contact_messages(name,email,subject,message) VALUES($1,$2,$3,$4)',[b.name,b.email,b.subject,b.message]);else memory.contacts.push({...b,createdAt:new Date().toISOString()});return json(res,201,{ok:true});}
  if(p==='/api/proposals'&&req.method==='POST'){const b=await body(req);if(!b.appel||!b.name||!b.email||!b.title||!b.summary)return json(res,400,{message:'Champs requis manquants.'});const ref='PROP-2026-'+String(Math.floor(1000+Math.random()*9000));if(pool)await query('INSERT INTO proposals(ref,appel,name,email,title,summary,message,file_name) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[ref,b.appel,b.name,b.email,b.title,b.summary,b.message||'',b.fileName||'']);else memory.proposals.push({ref,...b,status:'En attente',createdAt:new Date().toISOString()});return json(res,201,{ok:true,ref});}
  if(p==='/api/admin/state'&&req.method==='GET'){if(!user||user.role!=='owner')return json(res,403,{message:'Accès administrateur requis.'});return json(res,200,{state:await getAdminState()});}
  if(p==='/api/admin/state'&&req.method==='PATCH'){if(!user||user.role!=='owner')return json(res,403,{message:'Accès administrateur requis.'});const b=await body(req);if(!b.collection||!b.key||!b.action)return json(res,400,{message:'État invalide.'});return json(res,200,{state:await updateAdminState(b)});}
  if(p==='/api/admin/settings'&&req.method==='PUT'){if(!user||user.role!=='owner')return json(res,403,{message:'Accès administrateur requis.'});const b=await body(req);if(pool){for(const [k,v] of Object.entries({name:b.name||'',tagline:b.tagline||''}))await query('INSERT INTO site_settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value',[k,v]);}else memory.settings={...memory.settings,...b};return json(res,200,{ok:true});}
  return json(res,404,{message:'API route introuvable.'});
}

const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.xml':'application/xml; charset=utf-8','.txt':'text/plain; charset=utf-8'};
async function serveStatic(req,res,url){let relPath=decodeURIComponent(url.pathname);if(relPath==='/'||relPath.endsWith('/'))relPath += 'index.html';let file=path.normalize(path.join(SITE_ROOT,relPath));if(!file.startsWith(SITE_ROOT))return json(res,403,{message:'Forbidden'});try{const st=await fs.stat(file);if(!st.isFile())throw new Error('not-file');const data=await fs.readFile(file);const ext=path.extname(file);htmlHeaders(res,mime[ext]||'application/octet-stream');if(ext==='.css'||ext==='.js'||ext==='.svg')res.setHeader('Cache-Control','public, max-age=3600');res.writeHead(200);res.end(data);}catch{const fallback=path.join(SITE_ROOT,'404.html');try{const data=await fs.readFile(fallback);htmlHeaders(res);res.writeHead(404);res.end(data);}catch{res.writeHead(404);res.end('Not found');}}}

await fs.mkdir(SITE_ROOT,{recursive:true});
await initDb().catch(async e=>{console.error('DB init failed:',e.message);if(DEMO_MODE){await pool?.end().catch(()=>{});pool=null;}else{console.error('DEMO_MODE=false requires a working DATABASE_URL.');process.exit(1);}});
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(url.pathname.startsWith('/api/'))return await api(req,res,url);return await serveStatic(req,res,url);}catch(e){console.error(e);return json(res,500,{message:'Erreur serveur.'});}});
server.listen(PORT,()=>console.log(`SOPHIA server listening on ${PORT} — ${pool?'Neon/Postgres enabled':'memory fallback'} — demo=${DEMO_MODE}`));
process.on('SIGTERM',async()=>{await pool?.end();server.close();});
