-- SOPHIA production/demo database schema for Neon PostgreSQL.
-- The Render server auto-creates these tables; this file is provided for manual inspection/migration.
CREATE TABLE IF NOT EXISTS users (id BIGSERIAL PRIMARY KEY,email TEXT NOT NULL UNIQUE,name TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'member',password_hash TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS purchases (id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,ref TEXT NOT NULL UNIQUE,slug TEXT NOT NULL,kind TEXT NOT NULL,title TEXT NOT NULL,price_cents INTEGER NOT NULL,url TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user_id,slug));
CREATE TABLE IF NOT EXISTS saved_articles (user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,slug TEXT NOT NULL,title TEXT NOT NULL,category TEXT NOT NULL,url TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(user_id,slug));
CREATE TABLE IF NOT EXISTS newsletter_subscribers (email TEXT PRIMARY KEY,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS contact_messages (id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL,subject TEXT NOT NULL,message TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS proposals (id BIGSERIAL PRIMARY KEY,ref TEXT NOT NULL UNIQUE,appel TEXT NOT NULL,name TEXT NOT NULL,email TEXT NOT NULL,title TEXT NOT NULL,summary TEXT NOT NULL,message TEXT NOT NULL,file_name TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'En attente',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS admin_state (key TEXT PRIMARY KEY,value JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS site_settings (key TEXT PRIMARY KEY,value TEXT NOT NULL);
